---
config:
  theme: neutral
  look: classic
  themeVariables:
    fontSize: 24px
---
erDiagram
    CARS {
        string id
        string brand
        string model
        string licensePlate
        string status
        string transmissionType
        string powertrainType
        string bodyType
        string driveType
        string color
        int64 year
        int64 mileage
        int64 pricePerDay
        int64 seats
        int64 averageRating
        int64 ratingCount
        map battery
        map engine
        array images
        boolean isLocked
        geopoint location
    }

    ENGINE {
        string fuelType
        double displacement
    }

    BATTERY {
        int64 capacity
        int64 range
    }

    LOCATION {
        double latitude
        double longitude
    }

    USERS {
        string id
        string firstName
        string lastName
        string email
        string phone
        string role
        string verificationStatus
        boolean isBlocked
        timestamp birthDate
        timestamp createdAt
    }

    BOOKINGS {
        string id
        string carId
        string userId
        string tripId
        string status
        int64 price
        timestamp plannedStart
        timestamp plannedEnd
        timestamp expiresAt
        timestamp createdAt
    }

    TRIPS {
        string id
        string carId
        string userId
        string bookingId
        string conditionStartId
        string conditionEndId
        string status
        int64 price
        int64 additionalCharge
        int64 totalPrice
        int64 rating
        timestamp actualStart
        timestamp actualEnd
        geopoint startLocation
        geopoint endLocation
    }

    CAR_CONDITIONS {
        string id
        string carId
        string userId
        string tripId
        string conditionType
        string description
        int64 mileage
        array images
        map energyLevel
        timestamp createdAt
    }

    ENERGY_LEVEL {
        int64 batteryPercent
        int64 fuelPercent
    }

    CARS ||--|| ENGINE : "містить"
    CARS ||--|| BATTERY : "містить"
    CARS ||--|| LOCATION : "має місцезнаходження"

    CARS ||--o| BOOKINGS : "пов’язаний з"
    CARS ||--o| TRIPS : "використовується у"

    USERS ||--o| BOOKINGS : "створює"
    USERS ||--o| TRIPS : "виконує"

    BOOKINGS ||--|| TRIPS : "ініціює"

    TRIPS ||--|| CAR_CONDITIONS : "початкова фотофіксація"
    TRIPS ||--|| CAR_CONDITIONS : "кінцева фотофіксація"

    TRIPS ||--|| LOCATION : "початкове місцезнаходження"
    TRIPS ||--|| LOCATION : "кінцеве місцезнаходження"

    CAR_CONDITIONS ||--|| ENERGY_LEVEL : "містить"